# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Connect to Chrome Remote
#'
#' @param url ws URL
#' @export
chrome_connect <- function(url) {
    .Call('decapitated_chrome_connect', PACKAGE = 'decapitated', url)
}

#' Instrument Chrome
#'
#' @export
instrument <- function(ws_ptr, cmd) {
    .Call('decapitated_instrument', PACKAGE = 'decapitated', ws_ptr, cmd)
}

